### ISSUE TITLE
TODO GUI

### ISSUE THREAD

**Issue by madevelascom** [mvelasco93/Kaixo#1]
## Pendientes
- [x] Tamaño definido de botones (TODOS): 120x35
- [x] Nada de tamaños de ventana con números impares. Todos los tamaños deben ser múltiplos de 10
- [ ] Añadir el icono a cada ventana
## Importantes
- Usar nombres representativos de clases y fxml
-  Campos de agregar/editar usan la misma ventana. No hace falta de tenerlos en ventanas separadas (Agregar, editar consulta)
- Todos los fxml deben de usar "Style.css" 
- Todos los fxml deben estar asociados a su controller
- Todos los labels deben de estar alineados al text field que les corresponde
- Poner los botones en un HBOX en la parte de abajo del grid con spacing de 20 entre los elementos (Layout HBox: Internal, Spacing)
